import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Clasificación ODSs</title>
        <meta name="Pagina principal" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Bienvenido a <strong>ODS-IA</strong> del <a href="https://colombia.unfpa.org">UNFPA!</a>
        </h1>

        <p className={styles.description}>
          Usando inteligencia artificial, esta herramienta permite clasificar los ODSs de acuerdo a su relevancia en el territorio.
        </p>

        <div className={styles.grid}>

          <a href="" className={styles.card}>
            <h2>Participar &#9995;</h2>
            <p>Responde algunas preguntas que permiten encontrar los ODSs mas relevantes para ti.</p>
          </a>

          <a
            href=""
            className={styles.card}
          >
            <h2>Resultados &#x1F50E;</h2>
            <p>Consulta los ODSs mas relevantes para las personas de tu ciudad o municipio.</p>
          </a>

          <a
            href=""
            className={styles.card}
          >
            <h2>Conocer mas &#x1F4DA;</h2>
            <p>
              Conoce mas de esta iniciativa y sobre que son los Objetivos de Desarrollo Sostenibles.
            </p>
          </a>
        </div>

      </main>
      <footer className={styles.footer}>
        <a
          href="https://github.com/amartinez1224"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created by Andrés Martínez{' '}
          <span className={styles.logo}>
            <Image src="/github.png" alt="GitHub log" width={16} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
